#!/bin/sh

for arg in --headless --disable-gpu "$@" ${CHROME_ARGUMENTS}; do
	[ -z "${arg}" -o "${uargs#*|${arg%%=*}|}" != "${uargs}" ] && continue
	uargs="${uargs}|${arg%%=*}|"
	[ "${arg%%=*}" = "--process-timeout" ] && CHROME_TIMEOUT=${arg#--process-timeout=} && continue
	args="${args} ${arg}"
done
cmd="/opt/google/chrome/chrome ${args}"
test "${CHROME_TIMEOUT}" -gt 0 2>/dev/null && cmd="timeout -t ${CHROME_TIMEOUT} ${cmd}"
exec ${cmd}
